body:
  - type: checkboxes
    attributes:
      label: Contribution guidelines
      options:
      - label: I've read the [contribution guidelines](https://tvdboom.github.io/ATOM/contributing/).
        required: true
  - type: radio
    default: one
    attributes:
      label: Type of change
      description: Indicate what this PR does.
      options:
      - one: Code style/documentation update (typos, formatting, local variables, etc...).
      - two: Bug fix (non-breaking change which fixes an issue).
      - three: New feature (non-breaking change which adds functionality).
      - four: Breaking change (fix or feature that would cause existing functionality to stop working).
      - Other
  - type: textarea
    attributes:
      label: Description
      description: Describe the changes you've made.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Info about issue or bug.
      description: Annotate the issue number that will be closed through this PR.
      value: "Fixes: #[issue number]"
  - type: checkboxes
    attributes:
      label: Checklist
      options:
      - label: My code follows the style guidelines of this project.
      - label: I have performed a self-review of my own code.
      - label: I have commented my code, particularly in hard-to-understand areas.
      - label: I have made corresponding changes to the documentation.
      - label: My changes generate no new warnings.
      - label: I have added tests that prove my fix is effective or that my feature works.
      - label: New and existing unit tests pass locally with my changes.
      - label: Any dependent changes have been merged and published in downstream modules.
