site_name: ATOM
site_url: http://tvdboom.github.io/ATOM
site_author: tvdboom
site_description: Documentation for ATOM, a Python AutoML package for fast exploration and experimentation of supervised machine learning pipelines.

repo_url: https://github.com/tvdboom/ATOM
edit_uri: ''
docs_dir: docs_sources/
site_dir: docs/
theme: lumen

markdown_extensions:
  - tables
  - fenced_code
  - admonition

copyright: © Copyright 2020, by tvdboom.

nav:
- Getting started: getting_started.md
- User guide: user_guide.md
- API:
    - ATOM:
        - ATOMClassifier: API/ATOM/atomclassifier.md
        - ATOMRegressor: API/ATOM/atomregressor.md
        - ATOMLoader: API/ATOM/atomloader.md
    - Data cleaning:
         - Scaler: API/data_cleaning/scaler.md
         - StandardCleaner: API/data_cleaning/standard_cleaner.md
         - Imputer: API/data_cleaning/imputer.md
         - Encoder: API/data_cleaning/encoder.md
         - Outliers: API/data_cleaning/outliers.md
         - Balancer: API/data_cleaning/balancer.md
    - Feature engineering:
        - FetaureGenerator: API/feature_engineering/feature_generator.md
        - FetaureSelector: API/feature_engineering/feature_selector.md
    - Training:
        - Trainer:
           - TrainerClassifier: API/training/trainerclassifier.md
           - TrainerRegressor: API/training/trainerregressor.md
        - SuccessiveHalving:
            - SuccessiveHalvingClassifier: API/training/successivehalvingclassifier.md
            - SuccessiveHalvingClassifier: API/training/successivehalvingregressor.md
        - TrainSizing:
            - TrainSizingClassifier: API/training/trainsizingclassifier.md
            - TrainSizingRegressor: API/training/trainsizingregressor.md
    - Prediction methods:
          - transform: API/prediction_methods/transform.md
          - predict: API/prediction_methods/predict.md
          - predict_proba: API/prediction_methods/predict_proba.md
          - predict_log_proba: API/prediction_methods/predict_log_proba.md
          - decision_function: API/prediction_methods/decision_function.md
          - score: API/prediction_methods/score.md
    - Plots:
        - plot_correlation: API/plots/plot_correlation.md
        - plot_pipeline: API/plots/plot_pipeline.md
        - plot_pca: API/plots/plot_pca.md
        - plot_components: API/plots/plot_components.md
        - plot_rfecv: API/plots/plot_rfecv.md
        - plot_successive_halving: API/plots/plot_successive_halving.md
        - plot_learning_curve: API/plots/plot_learning_curve.md
        - plot_bagging: API/plots/plot_bagging.md
        - plot_bo: API/plots/plot_bo.md
        - plot_evals: API/plots/plot_evals.md
        - plot_roc: API/plots/plot_roc.md
        - plot_prc: API/plots/plot_prc.md
        - plot_permutation_importance: API/plots/plot_permutation_importance.md
        - plot_feature_importance: API/plots/plot_feature_importance.md
        - plot_partial_dependence: API/plots/plot_partial_dependence.md
        - plot_errors: API/plots/plot_errors.md
        - plot_residuals: API/plots/plot_residuals.md
        - plot_confusion_matrix: API/plots/plot_confusion_matrix.md
        - plot_threshold: API/plots/plot_threshold.md
        - plot_probabilities: API/plots/plot_probabilities.md
        - plot_calibration: API/plots/plot_calibration.md
        - plot_gains: API/plots/plot_gains.md
        - plot_lift: API/plots/plot_lift.md
        - force_plot: API/plots/force_plot.md
        - dependence_plot: API/plots/dependence_plot.md
        - summary_plot: API/plots/summary_plot.md
        - decision_plot: API/plots/decision_plot.md
- Examples:
    - Binary classification: examples/binary_classification/binary_classification.md
    - Multiclass_classification: examples/multiclass_classification/multiclass_classification.md
    - Regression: examples/regression/regression.md
    - Successive halving: examples/successive_halving/successive_halving.md
    - Train sizing: examples/train_sizing/train_sizing.md
    - Feature engineering: examples/feature_engineering/feature_engineering.md
    - Multi-metric: examples/multi_metric/multi_metric.md
    - Early stopping: examples/early_stopping/early_stopping.md
    - Calibration: examples/calibration/calibration.md
- Dependencies: dependencies.md
- License: license.md
