name: ":bug: Bug Report"
description: Report a bug.
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Contribution guidelines
      description: Make sure that your request fulfills all the following requirements.
      options:
      - label: I've read the [contribution guidelines](https://tvdboom.github.io/ATOM/contributing/).
        required: true
      - label: The documentation does not mention anything about my problem.
      - label: There are no open or closed issues that are related to my problem.
  - type: textarea
    attributes:
      label: Description
      description: Provide a brief description of the bug in 1-2 sentences.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: Describe what you'd expect to happen.
  - type: textarea
    attributes:
      label: Actual behaviour
      description: Describe what is actually happening.
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Paste a minimal example to reproduce the bug.
  - type: textarea
    attributes:
      label: Python and package version
      description: Provide the used versions, i.e. run the following commands in the console.
      value: |
        - Python: `import sys; sys.version`
        - ATOM: `import atom; atom.__version__`
