name: ATOM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pytest
        python -m pip install --upgrade coverage
        python -m pip install --upgrade codecov
        python -m pip install --upgrade tensorflow
        python -m pip install --upgrade keras
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: coverage run -m pytest
    - name: Get coverage
      run: codecov
