name: ATOM

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - name: Check imports
        uses: jamescurtin/isort-action@master
        with:
          sortPaths: atom tests

  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - name: Apply linting
        uses: py-actions/flake8@v2
        with:
          path: atom tests

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -U pytest
          pip install -U coverage
          pip install -U tensorflow
          pip install -r requirements.txt
          pip install -r requirements-optional.txt
          pip install werkzeug==2.0.0
      - name: Run tests
        run: coverage run -m pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
